name: Build Windows binaries

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  VERSION: 3.24.24-2

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: temp
    - name: Move Checkout
      run: |
        Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-binutils
          patch
          curl
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-gtk-doc
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-gobject-introspection
          mingw-w64-x86_64-sassc
          mingw-w64-x86_64-libxslt
          mingw-w64-x86_64-gcc-libs
          mingw-w64-x86_64-adwaita-icon-theme
          mingw-w64-x86_64-atk
          mingw-w64-x86_64-cairo
          mingw-w64-x86_64-gdk-pixbuf2
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-json-glib
          mingw-w64-x86_64-libepoxy
          mingw-w64-x86_64-pango
          mingw-w64-x86_64-shared-mime-info

    - name: Build
      shell: msys2 {0}
      run: makepkg -s --noconfirm
      working-directory: C:/_/mingw-w64-gtk3

    - name: "Upload binaries"
      uses: actions/upload-artifact@v2
      with:
        path: C:/_/mingw-w64-gtk3/*.pkg.tar.*

    - name: Upload to bintray
      if: ${{ github.ref == 'refs/heads/master' }}
      shell: msys2 {0}
      run: |
        curl -T mingw-w64-x86_64-gtk3-horizon-${{ env.VERSION }}-any.pkg.tar.zst                  -ucarrotindustries:${{ secrets.BINTRAY_API_KEY }} https://api.bintray.com/content/carrotindustries/gtk3-horizon/gtk3-horizon/${{ env.VERSION }}/mingw-w64-x86_64-gtk3-horizon-${{ env.VERSION }}-any.pkg.tar.zst                  -H 'X-Bintray-Publish: 1'
        curl -T mingw-w64-x86_64-gtk-update-icon-cache-horizon-${{ env.VERSION }}-any.pkg.tar.zst -ucarrotindustries:${{ secrets.BINTRAY_API_KEY }} https://api.bintray.com/content/carrotindustries/gtk3-horizon/gtk3-horizon/${{ env.VERSION }}/mingw-w64-x86_64-gtk-update-icon-cache-horizon-${{ env.VERSION }}-any.pkg.tar.zst -H 'X-Bintray-Publish: 1'
      working-directory: C:/_/mingw-w64-gtk3
